# Generated by Django 5.1.6 on 2025-04-24 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
        ('shortlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_shortlist',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.job'),
        ),
        migrations.DeleteModel(
            name='Job_shortlist',
        ),
    ]
