# Generated by Django 5.1.6 on 2025-04-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(default=1, upload_to='applications/resumes/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
